development:
  adapter: postgresql
  encoding: unicode
  database: wakeup_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: wakeup_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: wakeup_production
  pool: 5
  host: localhost
